name: GitHub pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pdoc3 and dependancies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pdoc3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate documentation
      run: |
        pdoc3 --html ./src -o ./out --force --template-dir ${{ github.workspace }}/docs/pdoc3
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN  }}
        publish_dir: ./out
        
